Style/StringLiterals:
  EnforcedStyle: double_quotes

Layout/IndentHash:
  EnforcedStyle: consistent

Layout/MultilineHashBraceLayout:
  EnforcedStyle: same_line

Layout/SpaceInsideHashLiteralBraces:
  Enabled: false

Layout/MultilineMethodCallBraceLayout:
  EnforcedStyle: same_line
