Style/StringLiterals:
  EnforcedStyle: double_quotes

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Layout/MultilineMethodCallBraceLayout:
  EnforcedStyle: same_line

Layout/MultilineHashBraceLayout:
  EnforcedStyle: same_line

Layout/DotPosition:
  EnforcedStyle: trailing
