#+title: Spacemacs Config

This file is loaded by Spacemacs at startup.
It must be stored in your home directory.

#+begin_src elisp
;; -*- mode: emacs-lisp -*-
#+end_src

* TABLE OF CONTENTS :toc:
- [[#layers][LAYERS]]
  - [[#distribution][distribution]]
  - [[#enable-lazy-installation][enable-lazy-installation]]
  - [[#ask-for-lazy-installation][ask-for-lazy-installation]]
  - [[#configuration-layer-path][configuration-layer-path]]
  - [[#configuration-layers][configuration-layers]]
  - [[#additional-packages][additional-packages]]
  - [[#frozen-packages][frozen-packages]]
  - [[#excluded-packages][excluded-packages]]
  - [[#install-packages][install-packages]]
- [[#init][INIT]]
  - [[#elpa-https][elpa-https]]
  - [[#elpa-timeout][elpa-timeout]]
  - [[#check-for-update][check-for-update]]
  - [[#elpa-subdirectory][elpa-subdirectory]]
  - [[#editing-style][editing-style]]
  - [[#verbose-loading][verbose-loading]]
  - [[#startup-banner][startup-banner]]
  - [[#startup-lists][startup-lists]]
  - [[#startup-buffer-responsive][startup-buffer-responsive]]
  - [[#scratch-mode][scratch-mode]]
  - [[#themes][themes]]
  - [[#colorize-cursor-according-to-state][colorize-cursor-according-to-state]]
  - [[#default-font][default-font]]
  - [[#leader-key][leader-key]]
  - [[#emacs-command-key][emacs-command-key]]
  - [[#ex-command-key][ex-command-key]]
  - [[#emacs-leader-key][emacs-leader-key]]
  - [[#major-mode-leader-key][major-mode-leader-key]]
  - [[#major-mode-emacs-leader-key][major-mode-emacs-leader-key]]
  - [[#distinguish-gui-tab][distinguish-gui-tab]]
  - [[#remap-y-to-y][remap-Y-to-y$]]
  - [[#retain-visual-state-on-shift][retain-visual-state-on-shift]]
  - [[#visual-line-move-text][visual-line-move-text]]
  - [[#ex-substitute-global][ex-substitute-global]]
  - [[#default-layout-name][default-layout-name]]
  - [[#display-default-layout][display-default-layout]]
  - [[#auto-resume-layouts][auto-resume-layouts]]
  - [[#large-file-size][large-file-size]]
  - [[#auto-save-file-location][auto-save-file-location]]
  - [[#max-rollback-slots][max-rollback-slots]]
  - [[#helm-resize][helm-resize]]
  - [[#helm-no-header][helm-no-header]]
  - [[#helm-position][helm-position]]
  - [[#helm-use-fuzzy][helm-use-fuzzy]]
  - [[#enable-paste-transient-state][enable-paste-transient-state]]
  - [[#which-key-delay][which-key-delay]]
  - [[#which-key-position][which-key-position]]
  - [[#loading-progress-bar][loading-progress-bar]]
  - [[#fullscreen-at-startup][fullscreen-at-startup]]
  - [[#fullscreen-use-non-native][fullscreen-use-non-native]]
  - [[#maximized-at-startup][maximized-at-startup]]
  - [[#active-transparency][active-transparency]]
  - [[#inactive-transparency][inactive-transparency]]
  - [[#show-transient-state-title][show-transient-state-title]]
  - [[#show-transient-state-color-guide][show-transient-state-color-guide]]
  - [[#mode-line-unicode-symbols][mode-line-unicode-symbols]]
  - [[#smooth-scrolling][smooth-scrolling]]
  - [[#line-numbers][line-numbers]]
  - [[#folding-method][folding-method]]
  - [[#smartparens-strict-mode][smartparens-strict-mode]]
  - [[#smart-closing-parenthesis][smart-closing-parenthesis]]
  - [[#highlight-delimiters][highlight-delimiters]]
  - [[#persistent-server][persistent-server]]
  - [[#search-tools][search-tools]]
  - [[#default-package-repository][default-package-repository]]
  - [[#whitespace-cleanup][whitespace-cleanup]]

* LAYERS
Configuration Layers declaration.
You should not put any user code in this function besides modifying the variable values.
#+begin_src elisp
(defun dotspacemacs/layers ()
  (setq-default
#+end_src

** distribution
Base distribution to use. This is a layer contained in the directory *+distribution*. For now available distributions are *spacemacs-base* or *spacemacs*. (default *spacemacs*)
#+begin_src elisp
   dotspacemacs-distribution 'spacemacs
#+end_src
** enable-lazy-installation
Lazy installation of layers (i.e. layers are installed only when a file with a supported type is opened). Possible values are *all*, *unused* and *nil*. *unused* will lazy install only unused layers (i.e. layers not listed in variable *dotspacemacs-configuration-layers*), *all* will lazy install any layer that support lazy installation even the layers listed in *dotspacemacs-configuration-layers*. *nil* disable the lazy installation feature and you have to explicitly list a layer in the variable *dotspacemacs-configuration-layers* to install it. (default *unused*)
#+begin_src elisp
   dotspacemacs-enable-lazy-installation 'unused
#+end_src
** ask-for-lazy-installation
If non-nil then Spacemacs will ask for confirmation before installing a layer lazily. (default *t*)
#+begin_src elisp
   dotspacemacs-ask-for-lazy-installation t
#+end_src
** configuration-layer-path
If non-nil layers with lazy install support are lazy installed.
List of additional paths where to look for configuration layers.
Paths must have a trailing slash (i.e. *~/.mycontribs/*)
#+begin_src elisp
   dotspacemacs-configuration-layer-path '()
#+end_src
** configuration-layers
List of configuration layers to load.
#+begin_src elisp
   dotspacemacs-configuration-layers
   '(
     markdown
     yaml
     haskell
     ruby
     lua
     ;; ----------------------------------------------------------------
     ;; Example of useful layers you may want to use right away.
     ;; Uncomment some layer names and press <SPC f e R> (Vim style) or
     ;; <M-m f e R> (Emacs style) to install them.
     ;; ----------------------------------------------------------------
     helm
     ;; auto-completion
     better-defaults
     emacs-lisp
     git
     ;; markdown
     org
     ;; (shell :variables
     ;;        shell-default-height 30
     ;;        shell-default-position 'bottom)
     spell-checking
     syntax-checking
     ;; version-control
     )
#+end_src
** additional-packages
List of additional packages that will be installed without being wrapped in a layer. If you need some configuration for these packages, then consider creating a layer. You can also put the configuration in *dotspacemacs/user-config*.
#+begin_src elisp
   dotspacemacs-additional-packages '(visual-fill-column
                                      darkroom)
#+end_src
** frozen-packages
A list of packages that cannot be updated.
#+begin_src elisp
   dotspacemacs-frozen-packages '()
#+end_src
** excluded-packages
A list of packages that will not be installed and loaded.
#+begin_src elisp
   dotspacemacs-excluded-packages '()
#+end_src
** install-packages
Defines the behaviour of Spacemacs when installing packages. Possible values are *used-only*, *used-but-keep-unused* and *all*. *used-only* installs only explicitly used packages and uninstall any unused packages as well as their unused dependencies. *used-but-keep-unused* installs only the used packages but won't uninstall them if they become unused. *all* installs /all/ packages supported by Spacemacs and never uninstall them. (default is *used-only*)
#+begin_src elisp
   dotspacemacs-install-packages 'used-only))
#+end_src


* INIT
Initialization function.
This function is called at the very startup of Spacemacs initialization before layers configuration.
You should not put any user code in there besides modifying the variable values.
This setq-default sexp is an exhaustive list of all the supported spacemacs settings.
#+begin_src elisp
(defun dotspacemacs/init ()
  (setq-default
#+end_src

** elpa-https
If non nil ELPA repositories are contacted via HTTPS whenever it's possible. Set it to *nil* if you have no way to use HTTPS in your environment, otherwise it is strongly recommended to let it set to t. This variable has no effect if Emacs is launched with the parameter *--insecure* which forces the value of this variable to *nil*. (default *t*)
#+begin_src elisp
   dotspacemacs-elpa-https t
#+end_src
** elpa-timeout
Maximum allowed time in seconds to contact an ELPA repository.
#+begin_src elisp
   dotspacemacs-elpa-timeout 5
#+end_src
** check-for-update
If non *nil* then spacemacs will check for updates at startup when the current branch is not *develop*. Note that checking for new versions works via git commands, thus it calls GitHub services whenever you start Emacs. (default *nil*)
#+begin_src elisp
   dotspacemacs-check-for-update nil
#+end_Sec
** elpa-subdirectory
If non-nil, a form that evaluates to a package directory. For example, to use different package directories for different Emacs versions, set this to *emacs-version*.
#+begin_src elisp
   dotspacemacs-elpa-subdirectory nil
#+end_src
** editing-style
One of *vim*, *emacs* or *hybrid*.
*hybrid* is like *vim* except that *insert state* is replaced by the *hybrid state* with *emacs* key bindings. The value can also be a list with *:variables* keyword (similar to layers). Check the editing styles section of the documentation for details on available variables. (default *vim*)
#+begin_src elisp
   dotspacemacs-editing-style 'vim
#+end_src
** verbose-loading
If non *nil* output loading progress in **Messages** buffer. (default *nil*)
#+begin_src elisp
   dotspacemacs-verbose-loading nil
#+end_src
** startup-banner
Specify the startup banner. Default value is *official*, it displays the official spacemacs logo. An integer value is the index of text banner, *random* chooses a random text banner in *core/banners* directory. A string value must be a path to an image format supported by your Emacs build.
If the value is nil then no banner is displayed. (default 'official)
#+begin_src elisp
   dotspacemacs-startup-banner 'official
#+end_src
** startup-lists
List of items to show in startup buffer or an association list of the form *(list-type . list-size)*. If *nil* then it is disabled.
Possible values for list-type are: *recents* *bookmarks* *projects* *agenda* *todos*.
List sizes may be *nil*, in which case *spacemacs-buffer-startup-lists-length* takes effect.
#+begin_src elisp
   dotspacemacs-startup-lists '((recents . 5)
                                (projects . 7))
#+end_src
** startup-buffer-responsive
True if the home buffer should respond to resize events.
#+begin_src elisp
   dotspacemacs-startup-buffer-responsive t
#+end_src
** scratch-mode
Default major mode of the scratch buffer (default *text-mode*)
#+begin_src elisp
   dotspacemacs-scratch-mode 'text-mode
#+end_src
** themes
List of themes, the first of the list is loaded when spacemacs starts.
Press *<SPC> T n* to cycle to the next theme in the list (works great with 2 themes variants, one dark and one light)
#+begin_src elisp
   dotspacemacs-themes '(solarized-light
                         solarized-dark)
#+end_src
** colorize-cursor-according-to-state
If non *nil* the cursor color matches the state color in GUI Emacs.
#+begin_src elisp
   dotspacemacs-colorize-cursor-according-to-state t
#+end_src
** default-font
Default font, or prioritized list of fonts. *powerline-scale* allows to
quickly tweak the mode-line size to make separators look not too crappy.
#+begin_src elisp
   dotspacemacs-default-font '("Hasklig"
                               :size 28
                               :weight normal
                               :width normal
                               :powerline-scale 1.1)
#+end_src
** leader-key
The leader key
#+begin_src elisp
   dotspacemacs-leader-key "SPC"
#+end_src
** emacs-command-key
The key used for Emacs commands (*M-x*) (after pressing on the leader key). (default *"SPC"*)
#+begin_src elisp
   dotspacemacs-emacs-command-key "SPC"
#+end_src
** ex-command-key
The key used for Vim Ex commands (default *":"*)
#+begin_src elisp
   dotspacemacs-ex-command-key ":"
#+end_src
** emacs-leader-key
The leader key accessible in *emacs state* and *insert state* (default *"M-m"*)
#+begin_src elisp
   dotspacemacs-emacs-leader-key "M-m"
#+end_src
** major-mode-leader-key
Major mode leader key is a shortcut key which is the equivalent of pressing *<leader> m*. Set it to *nil* to disable it. (default *","*)
#+begin_src elisp
   dotspacemacs-major-mode-leader-key ","
#+end_src
** major-mode-emacs-leader-key
Major mode leader key accessible in *emacs state* and *insert state*. (default *"C-M-m"*)
#+begin_src elisp
   dotspacemacs-major-mode-emacs-leader-key "C-M-m"
#+end_src
** distinguish-gui-tab
These variables control whether separate commands are bound in the GUI to the key pairs *C-i*, *TAB* and *C-m*, *RET*. Setting it to a non-*nil* value, allows for separate commands under *<C-i>* and *TAB* or *<C-m>* and *RET*. In the terminal, these pairs are generally indistinguishable, so this only works in the GUI. (default *nil*)
#+begin_src elisp
   dotspacemacs-distinguish-gui-tab nil
#+end_src
** remap-Y-to-y$
If non *nil* *Y* is remapped to *y$* in Evil states. (default *nil*)
#+begin_src elisp
   dotspacemacs-remap-Y-to-y$ nil
#+end_src
** retain-visual-state-on-shift
If non-*nil*, the shift mappings *<* and *>* retain visual state if used there. (default *t*)
#+begin_src elisp
   dotspacemacs-retain-visual-state-on-shift t
#+end_src
** visual-line-move-text
If non-*nil*, *J* and *K* move lines up and down when in visual mode. (default *nil*)
#+begin_src elisp
   dotspacemacs-visual-line-move-text nil
#+end_src
** ex-substitute-global
If non *nil*, inverse the meaning of *g* in *:substitute* Evil ex-command. (default *nil*)
#+begin_src elisp
   dotspacemacs-ex-substitute-global nil
#+end_src
** default-layout-name
Name of the default layout (default *"Default"*)
#+begin_src elisp
   dotspacemacs-default-layout-name "Default"
#+end_src
** display-default-layout
If non *nil* the default layout name is displayed in the mode-line. (default *nil*)
#+begin_src elisp
   dotspacemacs-display-default-layout nil
#+end_src
** auto-resume-layouts
If non *nil* then the last auto saved layouts are resume automatically upon start. (default *nil*)
#+begin_src elisp
   dotspacemacs-auto-resume-layouts nil
#+end_src
** large-file-size
Size (in MB) above which spacemacs will prompt to open the large file literally to avoid performance issues. Opening a file literally means that no major mode or minor modes are active. (default is *1*)
#+begin_src elisp
   dotspacemacs-large-file-size 1
#+end_src
** auto-save-file-location
Location where to auto-save files. Possible values are *original* to auto-save the file in-place, *cache* to auto-save the file to another file stored in the cache directory and *nil* to disable auto-saving. (default *cache*)
#+begin_src elisp
   dotspacemacs-auto-save-file-location 'original
#+end_src
** max-rollback-slots
Maximum number of rollback slots to keep in the cache. (default *5*)
#+begin_src elisp
   dotspacemacs-max-rollback-slots 5
#+end_src
** helm-resize
If non *nil*, *helm* will try to minimize the space it uses. (default *nil*)
#+begin_src elisp
   dotspacemacs-helm-resize nil
#+end_src
** helm-no-header
if non *nil*, the helm header is hidden when there is only one source. (default *nil*)
#+begin_src elisp
   dotspacemacs-helm-no-header nil
#+end_src
** helm-position
define the position to display *helm*, options are *bottom*, *top*, *left*, or *right*. (default *bottom*)
#+begin_src elisp
   dotspacemacs-helm-position 'bottom
#+end_src
** helm-use-fuzzy
Controls fuzzy matching in helm. If set to *always*, force fuzzy matching in all non-asynchronous sources. If set to *source*, preserve individual source settings. Else, disable fuzzy matching in all sources. (default *always*)
#+begin_src elisp
   dotspacemacs-helm-use-fuzzy 'always
#+end_src
** enable-paste-transient-state
If non *nil* the paste micro-state is enabled. When enabled pressing *p* several times cycle between the kill ring content. (default *nil*)
#+begin_src elisp
   dotspacemacs-enable-paste-transient-state nil
#+end_src
** which-key-delay
Which-key delay in seconds. The which-key buffer is the popup listing the commands bound to the current keystroke sequence. (default *0.4*)
#+begin_src elisp
   dotspacemacs-which-key-delay 0.4
#+end_src
** which-key-position
Which-key frame position. Possible values are *right*, *bottom* and *right-then-bottom*. *right-then-bottom* tries to display the frame to the right; if there is insufficient space it displays it at the bottom. (default *bottom*)
#+begin_src elisp
   dotspacemacs-which-key-position 'bottom
#+end_src
** loading-progress-bar
If non *nil* a progress bar is displayed when spacemacs is loading. This may increase the boot time on some systems and emacs builds, set it to *nil* to boost the loading time. (default *t*)
#+begin_src elisp
   dotspacemacs-loading-progress-bar nil
#+end_src
** fullscreen-at-startup
If non *nil* the frame is fullscreen when Emacs starts up. (default *nil*) (Emacs 24.4+ only)
#+begin_src elisp
   dotspacemacs-fullscreen-at-startup nil
#+end_src
** fullscreen-use-non-native
If non *nil* *spacemacs/toggle-fullscreen* will not use native fullscreen.
Use to disable fullscreen animations in OSX. (default *nil*)
#+begin_src elisp
   dotspacemacs-fullscreen-use-non-native nil
#+end_src
** maximized-at-startup
If non *nil* the frame is maximized when Emacs starts up. Takes effect only if *dotspacemacs-fullscreen-at-startup* is *nil*. (default *nil*) (Emacs 24.4+ only)
#+begin_src elisp
   dotspacemacs-maximized-at-startup t
#+end_src
** active-transparency
A value from the range (0..100), in increasing opacity, which describes the transparency level of a frame when it's active or selected. Transparency can be toggled through *toggle-transparency*. (default *90*)
#+begin_src elisp
   dotspacemacs-active-transparency 90
#+end_src
** inactive-transparency
A value from the range (0..100), in increasing opacity, which describes the transparency level of a frame when it's inactive or deselected. Transparency can be toggled through *toggle-transparency*. (default *90*)
#+begin_src elisp
   dotspacemacs-inactive-transparency 90
#+end_src
** show-transient-state-title
If non *nil* show the titles of transient states. (default *t*)
#+begin_src elisp
   dotspacemacs-show-transient-state-title t
#+end_src
** show-transient-state-color-guide
If non *nil* show the color guide hint for transient state keys. (default *t*)
#+begin_src elisp
   dotspacemacs-show-transient-state-color-guide t
#+end_src
** mode-line-unicode-symbols
If non *nil* unicode symbols are displayed in the mode line. (default *t*)
#+begin_src elisp
   dotspacemacs-mode-line-unicode-symbols t
#+end_src
** smooth-scrolling
If non *nil* smooth scrolling (native-scrolling) is enabled. Smooth scrolling overrides the default behavior of Emacs which recenters point when it reaches the top or bottom of the screen. (default *t*)
#+begin_src elisp
   dotspacemacs-smooth-scrolling t
#+end_src
** line-numbers
Control line numbers activation. If set to *t* or *relative* line numbers are turned on in all *prog-mode* and *text-mode* derivatives. If set to *relative*, line numbers are relative. (default *nil*)
#+begin_src elisp
   ;; This variable can also be set to a property list for finer control:
   ;; '(:relative nil
   ;;   :disabled-for-modes dired-mode
   ;;                       doc-view-mode
   ;;                       markdown-mode
   ;;                       org-mode
   ;;                       pdf-view-mode
   ;;                       text-mode
   ;;   :size-limit-kb 1000)
   dotspacemacs-line-numbers nil
#+end_src
** folding-method
Code folding method. Possible values are *evil* and *origami*. (default *evil*)
#+begin_src elisp
   dotspacemacs-folding-method 'evil
#+end_src
** smartparens-strict-mode
If non-*nil* smartparens-strict-mode will be enabled in programming modes. (default *nil*)
#+begin_src elisp
   dotspacemacs-smartparens-strict-mode nil
#+end_src
** smart-closing-parenthesis
If non-*nil* pressing the closing parenthesis *)* key in insert mode passes over any automatically added closing parenthesis, bracket, quote, etc… This can be temporary disabled by pressing *C-q* before *)*. (default *nil*)
#+begin_src elisp
   dotspacemacs-smart-closing-parenthesis nil
#+end_src
** highlight-delimiters
Select a scope to highlight delimiters. Possible values are *any*, *current*, *all* or *nil*. Default is *all* (highlight any scope and emphasis the current one). (default *all*)
#+begin_src elisp
   dotspacemacs-highlight-delimiters 'all
#+end_src
** persistent-server
If non *nil*, advise quit functions to keep server open when quitting. (default *nil*)
#+begin_src elisp
   dotspacemacs-persistent-server nil
#+end_src
** search-tools
List of search tool executable names. Spacemacs uses the first installed tool of the list. Supported tools are *ag*, *pt*, *ack* and *grep*. (default *'("ag" "pt" "ack" "grep")*)
#+begin_src elisp
   dotspacemacs-search-tools '("ag" "pt" "ack" "grep")
#+end_src
** default-package-repository
The default package repository used if no explicit repository has been specified with an installed package. Not used for now. (default *nil*)
#+begin_src elisp
   dotspacemacs-default-package-repository nil
#+end_src
** whitespace-cleanup
Delete whitespace while saving buffer. Possible values are *all* to aggressively delete empty line and long sequences of whitespace, *trailing* to delete only the whitespace at end of lines, *changed* to delete only whitespace for changed lines or *nil* to disable cleanup. (default *nil*)
#+begin_src elisp
   dotspacemacs-whitespace-cleanup nil
   ))
#+end_src
