#+title: Spacemacs Config

This file is loaded by Spacemacs at startup.
It must be stored in your home directory.

#+begin_src elisp
;; -*- mode: emacs-lisp -*-
#+end_src

* layers
Configuration Layers declaration.
You should not put any user code in this function besides modifying the variable values.
#+begin_src elisp
(defun dotspacemacs/layers ()
  (setq-default
#+end_src
** distribution
Base distribution to use. This is a layer contained in the directory `+distribution'. For now available distributions are `spacemacs-base' or `spacemacs'. (default 'spacemacs)
#+begin_src elisp
   dotspacemacs-distribution 'spacemacs
#+end_src
** enable-lazy-installation
Lazy installation of layers (i.e. layers are installed only when a file with a supported type is opened). Possible values are `all', `unused' and `nil'. `unused' will lazy install only unused layers (i.e. layers not listed in variable `dotspacemacs-configuration-layers'), `all' will lazy install any layer that support lazy installation even the layers listed in `dotspacemacs-configuration-layers'. `nil' disable the lazy installation feature and you have to explicitly list a layer in the variable `dotspacemacs-configuration-layers' to install it. (default 'unused)
#+begin_src elisp
   dotspacemacs-enable-lazy-installation 'unused
#+end_src
** ask-for-lazy-installation
If non-nil then Spacemacs will ask for confirmation before installing a layer lazily. (default t)
#+begin_src elisp
   dotspacemacs-ask-for-lazy-installation t
#+end_src
** configuration-layer-path
If non-nil layers with lazy install support are lazy installed.
List of additional paths where to look for configuration layers.
Paths must have a trailing slash (i.e. `~/.mycontribs/')
#+begin_src elisp
   dotspacemacs-configuration-layer-path '()
#+end_src
** configuration-layers
List of configuration layers to load.
#+begin_src elisp
   dotspacemacs-configuration-layers
   '(
     markdown
     yaml
     haskell
     ruby
     lua
     ;; ----------------------------------------------------------------
     ;; Example of useful layers you may want to use right away.
     ;; Uncomment some layer names and press <SPC f e R> (Vim style) or
     ;; <M-m f e R> (Emacs style) to install them.
     ;; ----------------------------------------------------------------
     helm
     ;; auto-completion
     better-defaults
     emacs-lisp
     git
     ;; markdown
     org
     ;; (shell :variables
     ;;        shell-default-height 30
     ;;        shell-default-position 'bottom)
     spell-checking
     syntax-checking
     ;; version-control
     )
#+end_src
** additional-packages
List of additional packages that will be installed without being wrapped in a layer. If you need some configuration for these packages, then consider creating a layer. You can also put the configuration in `dotspacemacs/user-config'.
#+begin_src elisp
   dotspacemacs-additional-packages '(visual-fill-column
                                      darkroom)
#+end_src
** frozen-packages
A list of packages that cannot be updated.
#+begin_src elisp
   dotspacemacs-frozen-packages '()
#+end_src
** excluded-packages
A list of packages that will not be installed and loaded.
#+begin_src elisp
   dotspacemacs-excluded-packages '()
#+end_src
** install-packages
Defines the behaviour of Spacemacs when installing packages. Possible values are `used-only`, `used-but-keep-unused' and `all'. `used-only' installs only explicitly used packages and uninstall any unused packages as well as their unused dependencies. `used-but-keep-unused' installs only the used packages but won't uninstall them if they become unused. `all' installs *all* packages supported by Spacemacs and never uninstall them. (default is `used-only')
#+begin_src elisp
   dotspacemacs-install-packages 'used-only))
#+end_src
