#! /usr/bin/env bash

resources="xrdb -query"

## Fetch the Colors
background=$(${resources} | grep -i background | tail -c 8)
foreground=$(${resources} | grep -i foreground | tail -c 8)
black=$(${resources}      | grep -i color8     | tail -c 8)
red=$(${resources}        | grep -i color9     | tail -c 8)
green=$(${resources}      | grep -i color10    | tail -c 8)
yellow=$(${resources}     | grep -i color11    | tail -c 8)
blue=$(${resources}       | grep -i color12    | tail -c 8)
magenta=$(${resources}    | grep -i color13    | tail -c 8)
cyan=$(${resources}       | grep -i color14    | tail -c 8)
white=$(${resources}      | grep -i color15    | tail -c 8)

## Fonts
font1="-windows-dina-medium-r-*-*-10-*-*-*-*-*-*-*"
# font2="-gohu-gohufont-bold-r-normal--14-100-100-100-c-80-iso10646-1"
# font3='-*-tamsyn-medium-r-normal-*-12-*-*-*-*-*-*-1'
# font4='-wuncon-siji-medium-r-normal--17-*-*-*-*-*-*-*'

## Dimentions
mon_w=$(xrandr | grep -o -G "current [0-9]*" | tail -c 5)
bar_w=$(expr $mon_w - 32)
bar_h=24
bar_x=16
bar_y=16
dimentions="${bar_w}x${bar_h}+${bar_x}+${bar_y}"

## Workspace info.
workspaces(){
  output=""
  desktop="$(i3-msg -t get_workspaces \
    | jq '.[].name' \
    | sed -e 's/^"//' -e 's/"$//')"
  
  for line in  $desktop; do
    output="$output %{A:i3-msg workspace $line:} \
    $(echo $line | sed s/^[0-9*]-//)%{A}"
  done
  
  echo $output
}

clock(){
  echo $(date '+%H:%M - %A, %B %d - %Y')
}

## Bar for compositor to turn into empty space around main bar.
echo | lemonbar -n bar_invisible -g "1x40" -p &

## Main bar.
while :; do
  echo " $(workspaces) %{r} $(clock) "
  sleep 1.0
done \
  | lemonbar -d \
    -g ${dimentions} \
    -B ${background} \
    -F ${foreground} \
    -f ${font1} \
  | while read line; do eval $line; done &
#while read line; do eval $line; done >/dev/null 2>&1 &
