#!/usr/bin/env bash

cd ~/Videos/youtube
vim .autodl.txt \
&& youtube-dl -a .autodl.txt \
&& echo > .autodl.txt

echo "Finished downloading videos."

# queue=$(realpath $1)

# if [[ -d $2 ]]; then
  # cd $2
# fi

# trap "exit" INT
# while read line || [[ -n $line ]]; do
  # youtube-dl $line
# done < $queue
# echo > $queue
