#!/usr/bin/env bash

list=~/.autodl.txt
cd $1
vim $list \
&& youtube-dl -a $list \
&& echo > $list

echo "Finished downloading videos."

# queue=$(realpath $1)

# if [[ -d $2 ]]; then
  # cd $2
# fi

# trap "exit" INT
# while read line || [[ -n $line ]]; do
  # youtube-dl $line
# done < $queue
# echo > $queue
