#! /usr/bin/env ruby

class Main
  def initialize
    @args = Arguments.new(args: ARGV)
    @line = @args.input.downcase
    @grid = @line.split.map(&:chars)
    @replacer = Replacer.new
    @filler = Filler.new(align: @args.align, padding: @args.padding)
    @joiner = Joiner.new
  end

  def run
    # @replacer.replace!(@grid.grid)
    @filler.fill!(@grid)
    LeftPadder.new.pad!(@grid)
    puts @joiner.join(@grid)
  end
end

class Joiner
  def join(grid)
    output = []
    grid.each do |row|
      output << row.join(" ")
    end
    output.join("\n")
  end
end

class Replacer
  def initialize
    @replacement = ":regional_indicator_%s:"
  end

  def replace!(grid)
    grid.map! { |row| row.map { |cell| @replacement % cell } }
  end
end

class Filler
  def initialize(opts)
    @padding = opts[:padding] || ":clap:"
  end

  def fill!(grid)
    grid.map! { |row| row_fill(row) }
  end

  def row_fill(row)
    row.zip(Array.new(row.length - 1) { @padding }).flatten.compact
  end
end

class MidPadder
  def initialize(opts = {})
    @padding = opts[:padding] || ":clap:"
  end

  def fill(grid)
    output = []
    grid.each do |row|
      output << row.zip(
        Array.new(row.length - 1) { @padding }
      ).flatten.compact
    end
    size = measure(output)
    output2 = []
    output.each do |row|
      line = []
      difference = [(size[:width] - row.length) / 2, 0].max
      buffer = Array.new(difference) { @padding }
      line << [buffer, row, buffer]
      output2 << line.flatten
    end
    output2
  end
end

class LeftPadder
  def initialize(opts = {})
    @padding = opts[:padding] || ":clap:"
  end

  def pad!(grid)
    width = grid.map(&:length).max
    grid.map! { |row| [row, ([@padding] * (width - row.length))].flatten }
  end
end

class RightPadder
  def initialize(opts = {})
    @align = opts[:align]
    @ruler = (opts[:ruler] || Ruler).new
    @padding = opts[:padding] || ":clap:"
  end

  def fill(grid)
    output = []
    size = @ruler.measure(grid)
    grid.each do |row|
      difference = size[:width] - row.length
      buffer = Array.new(difference) { @padding }
      output << [buffer, row].flatten
    end
    output
  end
end

class Ruler
end

class Arguments
  attr_reader :align, :padding, :input

  def initialize(opts)
    @align_map = {
      "middle" => MidPadder,
      "right" => RightPadder,
      "left" => LeftPadder}
    @padding = nil
    @align = LeftPadder
    @input = nil
    parse(opts[:args])
  end

  def parse(args)
    n = 0
    until n == args.length
      case args[n]
      when "-p"
        @padding = args[n + 1]
        n += 1
      when "-a"
        @align = @align_map[args[n + 1]]
        n += 1
      else
        @input = args[n]
      end
      n += 1
    end
  end
end

Main.new.run
