#! /usr/bin/env ruby

# Class for running the script
class Main
  def initialize
    @args = Arguments.new(
      arg_map: {"-p" => :padding, "-a" => :alignment}).parse(ARGV)
    @pad_map = {
      "middle" => MidPadder,
      "right" => RightPadder,
      "left" => LeftPadder}
    @grid = @args[:input].downcase.split.map(&:chars)
    @padder = @pad_map[@args[:alignment]].new(padding: @args[:padding])
    @filler = Filler.new(padding: @padder.padding)
    @replacer = Replacer.new
  end

  def run
    @replacer.replace!(@grid)
    @filler.fill!(@grid)
    @padder.pad!(@grid)
    puts @grid.map { |row| row.join(" ") }.join("\n")
  end
end

# Replaces a 2D array of characters with their discord emoji version
class Replacer
  def initialize
    @replacement = ":regional_indicator_%s:"
  end

  def replace!(grid)
    grid.map! { |row| row.map { |cell| @replacement % cell } }
  end
end

# Interleaves the rows of a 2D grid with a filler value
class Filler
  def initialize(opts)
    @padding = opts[:padding]
  end

  def fill!(grid)
    return if @padding.empty? # gotta save those CPU cycles
    grid.map! { |row| row_fill(row) }
  end

  def row_fill(row)
    row.zip(Array.new(row.length - 1) { @padding }).flatten.compact
  end
end

# Padder superclass. Holds methods for its children to use
class Padder
  attr_reader :padding

  def initialize(opts = {})
    @padding = opts[:padding] || ":clap:"
  end

  def pad!(grid)
    return if @padding.empty? # gotta save those CPU cycles
    @width = grid.map(&:length).max
    grid.map! { |row| row_pad(row) }
  end

  def margin(row)
    [@padding] * (@width - row.length)
  end
end

# Left justifies a 2D array by padding rows with a value
class LeftPadder < Padder
  def initialize(opts = {})
    @padding = opts[:padding] || ""
  end

  def row_pad(row)
    [row, margin(row)].flatten
  end
end

# Right justifies a 2D array by padding rows with a value
class RightPadder < Padder
  def row_pad(row)
    [margin(row), row].flatten
  end
end

# Center justifies a 2D array by padding rows with a value
class MidPadder < Padder
  def row_pad(row)
    half = margin(row).slice(0, margin(row).length / 2)
    [half, row, half].flatten
  end
end

# Parses command line arguments
class Arguments
  attr_reader :args

  def initialize(opts)
    @arg_map = opts[:arg_map]
    @line = opts[:line].reverse
  end

  def parse(line)
    until line.empty?
      arg = line.pop
      if @arg_map[arg]
        @args[@arg_map[arg]] = line.pop
      else
        @args[:input] = arg
      end
    end
  end
end

Main.new.run
