#! /usr/bin/env bash
root=$(df -h / | tail --lines 1 | awk '{print "["$3" / "$2"] ("$4" Free)"}')
case "$1" in
  "-h")
    echo "home: $(df -h /home \
      | tail --lines 1 | awk '{print "["$3" / "$2"] ("$4" Free)"}')" ;;
  "-r")
    echo "root: $(df -h / \
      | tail --lines 1 | awk '{print "["$3" / "$2"] ("$4" Free)"}')" ;;
esac
