#!/usr/bin/env python2.7
# -*- coding: utf-8 -*-
# vim:ts=2:sw=2:expandtab

import os
import xcb
import ctypes
from xcb.xproto import *
from PIL import Image,ImageFilter

XCB_MAP_STATE_VIEWABLE = 2

def screenshot():
  os.system('scrot /tmp/.i3lock.png')

class Xlib:
  def __init__(self):
    self.Xlib = ctypes.CDLL("libX11.so.6")
    self.XOpenDisplay = self.Xlib.XOpenDisplay
    self.XOpenDisplay.restype = ctypes.c_void_p
    self.XRootWindow = self.Xlib.XRootWindow
    self.XRootWindow.restype = ctypes.c_ulong
    self.XRootWindow.argtypes = [ctypes.c_void_p, ctypes.c_int]
    self.XCloseDisplay = self.Xlib.XCloseDisplay
    self.XCloseDisplay.argtypes = [ctypes.c_void_p]

def Xlib_fetch_root():
  X = Xlib()
  display = X.XOpenDisplay(None)
  w = X.XRootWindow(display, 0)
  X.XCloseDisplay(display)
  return w

def xcb_fetch_windows():
  """ Returns an array of rects of currently visible windows. """
  
  x = xcb.connect()
  root = Xlib_fetch_root()
  wmname = x.core.InternAtom(True, 7, "WM_NAME").reply().atom
  wmstring = x.core.InternAtom(True, 6, "STRING").reply().atom

  rects = []

  # iterate through top-level windows
  for child in x.core.QueryTree(root).reply().children:
    # make sure we only consider windows that are actually visible
    attributes = x.core.GetWindowAttributes(child).reply()
    if attributes.map_state != XCB_MAP_STATE_VIEWABLE:
      continue
    rect = x.core.GetGeometry(child).reply()
    try:
      for subchild in x.core.QueryTree(child).reply().children:
        wmname_result = x.core.GetProperty(False, subchild, wmname, wmstring, 0, 8).reply()
        wmname_str = "".join([chr(y) for y in wmname_result.value])
        if "bar_invisible" == wmname_str:
          raise LookupError
    except LookupError:
      continue
    rects += [rect]

  return rects

def obscure_image(image):
  """ Obscures the given image. """
  size = image.size
  pixel_size = 9
  if size[0] < 9 or size[1] < 9:
    return image
  image_f = image.filter(ImageFilter.MaxFilter)
  image_s = image_f.resize((size[0] / pixel_size, size[1] / pixel_size), Image.NEAREST)
  image_l = image_s.resize((size[0], size[1]), Image.NEAREST)

  return image_l

def obscure(rects):
  """ Takes an array of rects to obscure from the screenshot. """
  image = Image.open('/tmp/.i3lock.png')

  for rect in rects:
    area = (
      rect.x, rect.y,
      rect.x + rect.width,
      rect.y + rect.height
    )

    cropped = image.crop(area)
    cropped = obscure_image(cropped)
    image.paste(cropped, area)
  overlay = Image.open('/home/robin/Documents/source/scripts/src/locked.png')
  image.paste(overlay, tuple([(i-o)/2 for i,o in zip(image.size,overlay.size)]), overlay)
  image.save('/tmp/.i3lock.png')

def lock_screen():
  os.system('i3lock -i /tmp/.i3lock.png --insidevercolor   ffffff1c \
--insidewrongcolor ffffff1c \
--insidecolor      0000001c \
--ringvercolor     ffffff00 \
--ringwrongcolor   ffffff55 \
--ringcolor        0000003e \
--linecolor        00000000 \
--textcolor        00000000 \
--keyhlcolor       ffffff80 ')

if __name__ == '__main__':
  # 1: Take a screenshot.
  screenshot()

  # 2: Get the visible windows.
  rects = xcb_fetch_windows()

  # 3: Process the screenshot.
  obscure(rects)

  # 4: Lock the screen
  lock_screen()

